language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

services:
  - docker

script:
  # Build binary and run test
  - go build && go test -v -race ./...
  # Build docker image
  - docker build -t sinnott74/dockercloudfoundrydemo .

before_deploy:
  # Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  # Push image to docker
  - docker push sinnott74/dockercloudfoundrydemo

  # Deploy
  # Bluemix / IBM Cloud
deploy:
  - provider: cloudfoundry
    username: ${IBM_CLOUD_USER}
    #########################
    ## Add BLUEMIX_PASSWORD environment variable to your Travis project's settings
    ## https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
    #########################
    password: ${IBM_CLOUD_PASSWORD}
    organization: ${IBM_CLOUD_USER}
    space: staging
    region: eu-gb
    api: https://api.eu-gb.bluemix.net
